//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 12:05:07 PM CST 
//


package com.digiwack.retailreward;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CartItem" type="{http://digiwack.com/retailReward}CartItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ItemCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TotalCost" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RewardPoints" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartItem"
})
@XmlRootElement(name = "CartStatusResponse")
public class CartStatusResponse {

    @XmlElement(name = "CartItem", required = true)
    protected List<CartItemType> cartItem;
    @XmlAttribute(name = "ItemCount")
    protected Integer itemCount;
    @XmlAttribute(name = "TotalCost")
    protected Integer totalCost;
    @XmlAttribute(name = "RewardPoints")
    protected Integer rewardPoints;

    /**
     * Gets the value of the cartItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cartItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCartItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CartItemType }
     * 
     * 
     */
    public List<CartItemType> getCartItem() {
        if (cartItem == null) {
            cartItem = new ArrayList<CartItemType>();
        }
        return this.cartItem;
    }

    /**
     * Gets the value of the itemCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemCount(Integer value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the totalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalCost(Integer value) {
        this.totalCost = value;
    }

    /**
     * Gets the value of the rewardPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRewardPoints() {
        return rewardPoints;
    }

    /**
     * Sets the value of the rewardPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRewardPoints(Integer value) {
        this.rewardPoints = value;
    }

}
