//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 12:05:07 PM CST 
//


package com.digiwack.retailreward;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.digiwack.retailreward package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.digiwack.retailreward
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CartStatusRequest }
     * 
     */
    public CartStatusRequest createCartStatusRequest() {
        return new CartStatusRequest();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link AddItemRequest }
     * 
     */
    public AddItemRequest createAddItemRequest() {
        return new AddItemRequest();
    }

    /**
     * Create an instance of {@link RemoveItemRequest }
     * 
     */
    public RemoveItemRequest createRemoveItemRequest() {
        return new RemoveItemRequest();
    }

    /**
     * Create an instance of {@link CartStatusResponse }
     * 
     */
    public CartStatusResponse createCartStatusResponse() {
        return new CartStatusResponse();
    }

    /**
     * Create an instance of {@link CartItemType }
     * 
     */
    public CartItemType createCartItemType() {
        return new CartItemType();
    }

    /**
     * Create an instance of {@link InventoryResponse }
     * 
     */
    public InventoryResponse createInventoryResponse() {
        return new InventoryResponse();
    }

    /**
     * Create an instance of {@link InventoryItem }
     * 
     */
    public InventoryItem createInventoryItem() {
        return new InventoryItem();
    }

    /**
     * Create an instance of {@link InventoryRequest }
     * 
     */
    public InventoryRequest createInventoryRequest() {
        return new InventoryRequest();
    }

}
